### ISSUE TITLE
Autobump bbl version in Dockerfile

### ISSUE THREAD

**Issue by rowanjacobs** [cloudfoundry/bbl-state-resource#11]
The Dockerfile pins the version of `bbl` at 6.2.1, which isn't even the newest patch release of 6.2.x. It should probably be autobumped and a new image published to Dockerhub (and tagged with the `bbl` version) whenever a new version of `bbl` is released.

**Comment by cwlbraa** [comment]
is this true? I feel like the pipeline supplies a different value when it's building...

either way, I can't figure out what version of bbl I'm running when I use the resource...

**Comment by rowanjacobs** [comment]
Well, the latest update to the public Docker image was an hour ago, so I suspect you're right.

At the very least, maybe on a `put` or `get`, `bbl -v` should print to stderr? I may open a new issue or PR for that though.

**Comment by rowanjacobs** [comment]
Closed this in favor of #12
