### ISSUE TITLE
Random feedback / possible use cases

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bbl-state-resource#2]
Hi Infrastructure team!

Super excited to see a `bbl` resource, looking forward to giving it a spin once it's ready. Wanted to share some feedback based on my experiences developing the [terraform-resource](https://github.com/ljfranklin/terraform-resource) since I imagine the two resources will end up supporting similar workflows.

As you may have already noticed, adding support for different storage backends like GCP and S3 is a fair bit of work. It bloats your resource and anyone using `bbl` outside of concourse will have to re-roll the same logic. As a possible alternative, you could move that storage logic directly into `bbl`. The `terraform` CLI recently added [this feature](https://www.terraform.io/docs/backends/state.html) and it's pretty great. Once you've configured a storage backend, each `terraform apply` or `terraform destroy` automatically updates its state file in remote storage. If you were to make this change, now would be a great time as writing a migration path in your resource to move people from the resource storage to first-class `bbl` storage is [not fun](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#backend-migration).

In reading your tracker stories, it wasn't clear that the resource would initially be capable of managing dynamic environments in CI. More specially, I'd like the first job in my pipeline to do a `put: bbl-resource` and get an environment created with a random name. Subsequent jobs in that pipeline could use a passed constraint to point to that specific environment. The random name allows running multiple environments through the pipeline in parallel. Even better, the resource could output a `name` and `metadata` file to be compatible with the concourse [pool-resource](https://github.com/concourse/pool-resource). You could then use the `bbl-resource` to populate an entire pool of environments all with random names which could later be claimed in different pipelines. For the pipelines I've used on my past couple teams, support for dynamic environments would be a requirement to start using this resource.

Feel free to grab me for a chat if any of this sounds interesting.

**Comment by cwlbraa** [comment]
thanks for the feedback!

@evanfarrar has brought up the bbl storage backends feature narrative, but at least I had not yet thought about migration path problems. 

Randomly generated names are very to get with bbl, but the resource does not support them yet. pool-resource compatibility sounds like a great little feature story(s) to drive that out.

**Comment by cwlbraa** [comment]
@ljfranklin we've got `pool-resource` compatibility AND it plugs-and-plays with `bosh-deployment-resource`.

I feel your concerns about storage logic and there's definitely been some discussion of implementing that in bbl. luckily, because we control both codebases, the migration between concourse-controlled state uploads and bbl-controlled state uploads should be a bit easier --- we should be able to make the move without any input from the user provided that bbl supports that natively across all supported IAASes and we store gcp environment states in gcs, aws in s3, etc.
